### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by debashishsahu9t8** [Xed-Editor/Xed-Editor#215]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728538045163
LocalTime : Oct 10, 2024 10:57:25 AM

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = RMX3241
SECURITY_PATCH = 2024-06-05
BASE_OS = 
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = realme
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = realme
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = R.18503a2_1

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4006)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at de.Maxr1998.modernpreferences.Preference.getBoolean(Preferences.kt:321)
	at de.Maxr1998.modernpreferences.preferences.TwoStatePreference.onAttach$libsettings_release(TwoStatePreference.kt:58)
	at de.Maxr1998.modernpreferences.Preference.attachToScreen$libsettings_release(Preferences.kt:166)
	at de.Maxr1998.modernpreferences.PreferenceScreen.<init>(Preferences.kt:433)
	at de.Maxr1998.modernpreferences.PreferenceScreen.<init>(Unknown Source:0)
	at de.Maxr1998.modernpreferences.PreferenceScreen$Builder.build(Preferences.kt:563)
	at com.rk.xededitor.Settings.SettingsEditor.getScreen(SettingsEditor.kt:355)
	at com.rk.xededitor.Settings.SettingsEditor.onCreate(SettingsEditor.kt:44)
	at android.app.Activity.performCreate(Activity.java:8397)
	at android.app.Activity.performCreate(Activity.java:8370)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3837)
	... 12 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main' Unix Time : 1728538045163 LocalTime : Oct 10, 2024 10:57:25 AM
> 
> ACTIVE_CODENAMES = [] app_version = 2.7.3 device_model = RMX3241 SECURITY_PATCH = 2024-06-05 BASE_OS = RELEASE = 13 MEDIA_PERFORMANCE_CLASS = 0 CODENAME = REL manufacturer = realme RELEASE_OR_CODENAME = 13 RELEASE_OR_PREVIEW_DISPLAY = 13 KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair} SDK_INT = 33 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 33 brand = realme supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = R.18503a2_1
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean Error StackTrace :
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.Settings.SettingsEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3864) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4006) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:240) at android.os.Looper.loop(Looper.java:351) at android.app.ActivityThread.main(ActivityThread.java:8377) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345) at de.Maxr1998.modernpreferences.Preference.getBoolean(Preferences.kt:321) at de.Maxr1998.modernpreferences.preferences.TwoStatePreference.onAttach$libsettings_release(TwoStatePreference.kt:58) at de.Maxr1998.modernpreferences.Preference.attachToScreen$libsettings_release(Preferences.kt:166) at de.Maxr1998.modernpreferences.PreferenceScreen.(Preferences.kt:433) at de.Maxr1998.modernpreferences.PreferenceScreen.(Unknown Source:0) at de.Maxr1998.modernpreferences.PreferenceScreen$Builder.build(Preferences.kt:563) at com.rk.xededitor.Settings.SettingsEditor.getScreen(SettingsEditor.kt:355) at com.rk.xededitor.Settings.SettingsEditor.onCreate(SettingsEditor.kt:44) at android.app.Activity.performCreate(Activity.java:8397) at android.app.Activity.performCreate(Activity.java:8370) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3837) ... 12 more

clear app data to fix the issue
