### ISSUE TITLE
Crash Report: selecting text with Ctrl + Shift + Left Arrow

### ISSUE THREAD

**Issue by Brajesh3** [Xed-Editor/Xed-Editor#225]
```java
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728688073478
LocalTime : 12 Oct 2024 04:37:53

ACTIVE_CODENAMES = []
app_version = 2.7.4
device_model = SM-M115F
SEM_INT = 3101
SECURITY_PATCH = 2023-11-01
BASE_OS = samsung/m11qnnxx/m11q:12/SP1A.210812.016/M115FXXU5CWE3:user/release-keys
SEM_FIRST_SDK_INT = 29
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
SEM_PLATFORM_INT = 130100
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = M115FXXS5CWK3


Error Message : length=32; index=-1
Error Cause : null
Error StackTrace : 

java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1
	at B4.l.charAt(Unknown Source:31)
	at B4.q.a(Unknown Source:5)
	at v0.c.C(Unknown Source:45)
	at v0.c.q(Unknown Source:130)
	at F4.r.invoke(Unknown Source:103)
	at io.github.rosemoe.sora.widget.CodeEditor.W(Unknown Source:19)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(Unknown Source:1120)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3664)
	at android.view.View.dispatchKeyEvent(View.java:14927)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1004)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4225)
	at m1.k.superDispatchKeyEvent(Unknown Source:5)
	at v0.f.i(Unknown Source:10)
	at m1.k.dispatchKeyEvent(Unknown Source:26)
	at i.k.dispatchKeyEvent(Unknown Source:22)
	at i.x.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6539)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6403)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
## Additional Information
**this happen when i was selecting word by word with
`ctrl + shift + ←`
when it reach starting point/1st line it crashes**

**Comment by RohitKushvaha01** [comment]
@Brajesh3 try with latest commit

**Comment by Brajesh3** [comment]
```java
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728709861774
LocalTime : 12 Oct 2024 10:41:01

ACTIVE_CODENAMES = []
app_version = 2.7.4
device_model = SM-M115F
SEM_INT = 3101
SECURITY_PATCH = 2023-11-01
BASE_OS = samsung/m11qnnxx/m11q:12/SP1A.210812.016/M115FXXU5CWE3:user/release-keys
SEM_FIRST_SDK_INT = 29
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
SEM_PLATFORM_INT = 130100
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = M115FXXS5CWK3


Error Message : length=32; index=-1
Error Cause : null
Error StackTrace : 

java.lang.ArrayIndexOutOfBoundsException: length=32; index=-1
	at io.github.rosemoe.sora.text.ContentLine.charAt(ContentLine.java:272)
	at io.github.rosemoe.sora.text.ICUUtils.getWordRangeFallback(ICUUtils.java:72)
	at io.github.rosemoe.sora.text.ICUUtils.getWordRange(ICUUtils.java:61)
	at io.github.rosemoe.sora.util.Chars.getWordRange(Chars.kt:93)
	at io.github.rosemoe.sora.util.Chars.findWord(Chars.kt:76)
	at io.github.rosemoe.sora.util.Chars.prevWordStart(Chars.kt:39)
	at io.github.rosemoe.sora.widget.SelectionMovement._init_$lambda$4(SelectionMovement.kt:83)
	at io.github.rosemoe.sora.widget.SelectionMovement.$r8$lambda$54mfBKVl6kTY6njDImSkriDS2K0(Unknown Source:0)
	at io.github.rosemoe.sora.widget.SelectionMovement$$ExternalSyntheticLambda12.invoke(D8$$SyntheticClass:0)
	at io.github.rosemoe.sora.widget.SelectionMovement.getPositionAfterMovement(SelectionMovement.kt:197)
	at io.github.rosemoe.sora.widget.CodeEditor.extendSelection(CodeEditor.java:3277)
	at io.github.rosemoe.sora.widget.CodeEditor.moveOrExtendSelection(CodeEditor.java:3266)
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.handleKeyEvent(EditorKeyEventHandler.java:297)
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.onKeyDown(EditorKeyEventHandler.java:155)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:4677)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3664)
	at android.view.View.dispatchKeyEvent(View.java:14927)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1004)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4225)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6539)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6403)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
