### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cookiethieft** [Xed-Editor/Xed-Editor#228]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728821572282
LocalTime : 2024年10月13日 20:12:52

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = V2002A
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2023-02-01
BASE_OS = 
RELEASE = 10
CODENAME = REL
manufacturer = vivo
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 29
PREVIEW_SDK_INT = 0
SDK = 29
brand = vivo
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = compiler07191244

Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error StackTrace : 

java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5321)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5350)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7906)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
	at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
	at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
	at android.app.Activity.performDestroy(Activity.java:8123)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1388)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5306)
	... 11 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1728821572282
> LocalTime : 2024年10月13日 20:12:52
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = V2002A
> RESOURCES_SDK_INT = 29
> SECURITY_PATCH = 2023-02-01
> BASE_OS = 
> RELEASE = 10
> CODENAME = REL
> manufacturer = vivo
> SDK_INT = 29
> PREVIEW_SDK_FINGERPRINT = REL
> FIRST_SDK_INT = 29
> PREVIEW_SDK_INT = 0
> SDK = 29
> brand = vivo
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = compiler07191244
> 
> 
> Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5321)
> 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5350)
> 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
> 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loop(Looper.java:230)
> 	at android.app.ActivityThread.main(ActivityThread.java:7906)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> 	at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
> 	at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
> 	at android.app.Activity.performDestroy(Activity.java:8123)
> 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1388)
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5306)
> 	... 11 more
> 

You probably has internet connection
