### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MDDanish-max** [Xed-Editor/Xed-Editor#230]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1728904903457
LocalTime : 14 Oct 2024 15:51:43

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = 2209116AG
SECURITY_PATCH = 2024-08-01
BASE_OS = Redmi/sweet_global2/sweet:13/TKQ1.221114.001/V816.0.6.0.THGMIXM:user/release-keys
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V816.0.8.0.THGMIXM

Error Message : Failed to allocate a 224 byte allocation with 125816 free bytes and 122KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
Error Cause : null
Error StackTrace : 

java.lang.OutOfMemoryError: Failed to allocate a 224 byte allocation with 125816 free bytes and 122KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at io.github.rosemoe.sora.text.ContentLine.<init>(ContentLine.java:66)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:417)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:370)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:105)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:68)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:56)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.java:249)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.java:117)
	at android.app.Activity.performCreate(Activity.java:8589)
	at android.app.Activity.performCreate(Activity.java:8553)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1445)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4073)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2426)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1728904903457
> LocalTime : 14 Oct 2024 15:51:43
> 
> ACTIVE_CODENAMES = []
> app_version = 2.6.0
> device_model = 2209116AG
> SECURITY_PATCH = 2024-08-01
> BASE_OS = Redmi/sweet_global2/sweet:13/TKQ1.221114.001/V816.0.6.0.THGMIXM:user/release-keys
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> brand = Redmi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V816.0.8.0.THGMIXM
> 
> 
> Error Message : Failed to allocate a 224 byte allocation with 125816 free bytes and 122KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.OutOfMemoryError: Failed to allocate a 224 byte allocation with 125816 free bytes and 122KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
> 	at io.github.rosemoe.sora.text.ContentLine.<init>(ContentLine.java:66)
> 	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:417)
> 	at io.github.rosemoe.sora.text.Content.insert(Content.java:370)
> 	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:105)
> 	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:68)
> 	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:56)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.java:249)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.java:117)
> 	at android.app.Activity.performCreate(Activity.java:8589)
> 	at android.app.Activity.performCreate(Activity.java:8553)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1445)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4073)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2426)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:211)
> 	at android.os.Looper.loop(Looper.java:300)
> 	at android.app.ActivityThread.main(ActivityThread.java:8503)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
> 

Opening very large file is a bad idea
