### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jetrom17** [Xed-Editor/Xed-Editor#237]
I tried to run:

```java
class Demo {
    public static void main(String[] args) {
        int x = 6;
        int y = 3;

        System.out.println(x+y);
    }
}
```
Because I'm learning Java.

> [!CAUTION]
> Android 14.

``` 
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-3'
Unix Time : 1729108112474
LocalTime : 16 de out. de 2024 16:48:32

ACTIVE_CODENAMES = []
app_version = 2.7.4
device_model = moto g73 5G
SECURITY_PATCH = 2024-08-01
BASE_OS = motorola/devonf_g_sys/devonf:14/U1TN34.82-12-7/4cdf7-62b22:user/release-keys
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = motorola
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = motorola
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = f6f3b-00d08


Error Message : main.java: open failed: EROFS (Read-only file system)
Error Cause : android.system.ErrnoException: open failed: EROFS (Read-only file system)
Error StackTrace : 

java.io.FileNotFoundException: main.java: open failed: EROFS (Read-only file system)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:259)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:208)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:141)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:140)
	at com.rk.xededitor.MainActivity.editor.KarbonEditor$saveToFile$2.invokeSuspend(KarbonEditor.kt:92)
	at com.rk.xededitor.MainActivity.editor.KarbonEditor$saveToFile$2.invoke(Unknown Source:8)
	at com.rk.xededitor.MainActivity.editor.KarbonEditor$saveToFile$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.rk.xededitor.MainActivity.editor.KarbonEditor.saveToFile(KarbonEditor.kt:91)
	at com.rk.xededitor.MainActivity.editor.fragments.EditorFragment$save$1.invokeSuspend(EditorFragment.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(CustomScope), StandaloneCoroutine{Cancelling}@e329b07, Dispatchers.IO]
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8275)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 20 more

 ```

**Comment by Jetrom17** [comment]
![Screenshot_20241016-165257.png](https://github.com/user-attachments/assets/0e6571f1-f66f-401e-b3e8-9913ed8a27b6)

> [!IMPORTANT]
> Restarted the application and ran.

**Comment by trindadedev13** [comment]
maybe issue of Android 14, but idk

**Comment by RohitKushvaha01** [comment]
@Jetrom17 try clearing app data

**Comment by Jetrom17** [comment]
> maybe issue of Android 14, but idk

Yeah. Android 12 and above contains higher restrictions.

**Comment by Jetrom17** [comment]
> @Jetrom17 try clearing app data 

Ok. But I believe that this would not be an ideal solution. It would be a temporary solution.

**Comment by RohitKushvaha01** [comment]
> > @Jetrom17 try clearing app data 
> 
> Ok. But I believe that this would not be an ideal solution. It would be a temporary solution.

It's a ideal solution, don't forget you are on development build 😁

**Comment by Jetrom17** [comment]
> > > @Jetrom17 try clearing app data 
> > 
> > Ok. But I believe that this would not be an ideal solution. It would be a temporary solution.
> 
> It's a ideal solution, don't forget you are on development build 😁

What? I downloaded the release.

**Comment by RohitKushvaha01** [comment]
> > > > @Jetrom17 try clearing app data 
> > > 
> > > Ok. But I believe that this would not be an ideal solution. It would be a temporary solution.
> > 
> > It's a ideal solution, don't forget you are on development build 😁
> 
> What? I downloaded the release.

If you are on release how can you run java code ?

**Comment by RohitKushvaha01** [comment]
@Jetrom17 seen like there's a misunderstanding please explain your issue in details, what are you doing actually?

**Comment by trindadedev13** [comment]
> > > > @Jetrom17 try clearing app data
> > > 
> > > 
> > > Ok. But I believe that this would not be an ideal solution. It would be a temporary solution.
> > 
> > 
> > It's a ideal solution, don't forget you are on development build 😁
> 
> What? I downloaded the release.

Well, it's a build release, but not a stable release.

**Comment by trindadedev13** [comment]
let's say only github releases version, they are stable versions.

**Comment by Jetrom17** [comment]
> @Jetrom17 seems like there's a misunderstanding please explain your issue in details, what are you doing actually?

I tried to run the command:

```java
class Demo {
    public static void main(String[] args) {
        int x = 6;
        int y = 3;

        System.out.println(x+y);
    }
}
```

When I tried to run the error happened. But when I restarted the application, the code that was being executed and denied by Android started working again.

**Comment by Jetrom17** [comment]
> Well, it's a build release, but not a stable release.

I downloaded F-droid.

**Comment by RohitKushvaha01** [comment]
> > Well, it's a build release, but not a stable release.
> 
> I downloaded F-droid.
> 
> 

But the version 2.7.3 that is on f-droid doesn't have java Compiler it's a new addition, anyways we try to fix what is wrong

**Comment by Jetrom17** [comment]
> But the version 2.7.3 that is on f-droid doesn't have java Compiler it's a new addition, anyways we try to fix what is wrong

Ok. Thanks. I must have probably made a mistake with the versions distributed on Telegram and F-droid.

**Comment by RohitKushvaha01** [comment]
> ![Screenshot_20241016-165257.png](https://private-user-images.githubusercontent.com/72875404/377210822-0e6571f1-f66f-401e-b3e8-9913ed8a27b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDQ2MjcsIm5iZiI6MTcyOTE0NDMyNywicGF0aCI6Ii83Mjg3NTQwNC8zNzcyMTA4MjItMGU2NTcxZjEtZjY2Zi00MDFlLWIzZTgtOTkxM2VkOGEyN2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA1NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyODY4MmJkNTVlYjkzMGI3MjliOTc5YTdiNzZiOWM3ODdlMTM0MjkzNjc1YjdlNWRkNzQ5ODY1YTkyYzAwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W0VBBg3rXwFHxeXgRxgo4E7BMuck3o41jGBp4GfEtkA)
> 
> Important
> 
> Restarted the application and ran.

those scripts are not intended to be executed by users open the file the editor and click on the run button 

and about the error what file are you trring to access?
