### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by The-mfn-guy** [Xed-Editor/Xed-Editor#254]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1729388150232
LocalTime : Oct 19, 2024 8:35:50 PM

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = REVVL V+ 5G
SECURITY_PATCH = 2024-02-05
BASE_OS = 
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Wingtech
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
brand = T-Mobile
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = SW_S98115AA1_S_V122

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException
Error Cause : java.lang.NullPointerException
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3675)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.NullPointerException
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:170)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:79)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3648)
	... 12 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1729388150232
> LocalTime : Oct 19, 2024 8:35:50 PM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = REVVL V+ 5G
> SECURITY_PATCH = 2024-02-05
> BASE_OS = 
> RELEASE = 12
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Wingtech
> RELEASE_OR_CODENAME = 12
> SDK_INT = 31
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 31
> brand = T-Mobile
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = SW_S98115AA1_S_V122
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException
> Error Cause : java.lang.NullPointerException
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3675)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7881)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
> Caused by: java.lang.NullPointerException
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:170)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:79)
> 	at android.app.Activity.performCreate(Activity.java:8050)
> 	at android.app.Activity.performCreate(Activity.java:8030)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3648)
> 	... 12 more
> 

Already fixed in 2.7.4
