### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kekomenos** [Xed-Editor/Xed-Editor#258]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
Unix Time : 1730214241367
LocalTime : ۲۹ اکتبر ۲۰۲۴ ۱۸:۳۴:۰۱

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = SM-G965F
SEM_INT = 2903
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2022-03-01
BASE_OS = 
SEM_FIRST_SDK_INT = 26
RELEASE = 10
CODENAME = REL
manufacturer = samsung
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 26
PREVIEW_SDK_INT = 0
SDK = 29
SEM_PLATFORM_INT = 110500
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = G965FXXUHFVK1

Error Message : Permission Denial: writing com.sec.android.app.myfiles.external.providers.MyFilesFileProvider uri content://com.sec.android.app.myfiles.FileProvider/device_storage/Android/data/io.nekohasekai.sfa/Yacd-meta-gh-pages/apple-touch-icon-precomposed.png from pid=7572, uid=11487 requires the provider be exported, or grantUriPermission()
Error Cause : null
Error StackTrace : 

java.lang.SecurityException: Permission Denial: writing com.sec.android.app.myfiles.external.providers.MyFilesFileProvider uri content://com.sec.android.app.myfiles.FileProvider/device_storage/Android/data/io.nekohasekai.sfa/Yacd-meta-gh-pages/apple-touch-icon-precomposed.png from pid=7572, uid=11487 requires the provider be exported, or grantUriPermission()
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1535)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1241)
	at com.rk.xededitor.SimpleEditor.SimpleEditor$save$1.invokeSuspend(SimpleEditor.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d2097fd, Dispatchers.IO]

**Comment by kekomenos** [comment]
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1' Unix Time : 1730214241367 LocalTime : ۲۹ اکتبر ۲۰۲۴ ۱۸:۳۴:۰۱
> 
> ACTIVE_CODENAMES = [] app_version = 2.7.3 device_model = SM-G965F SEM_INT = 2903 RESOURCES_SDK_INT = 29 SECURITY_PATCH = 2022-03-01 BASE_OS = SEM_FIRST_SDK_INT = 26 RELEASE = 10 CODENAME = REL manufacturer = samsung SDK_INT = 29 PREVIEW_SDK_FINGERPRINT = REL FIRST_SDK_INT = 26 PREVIEW_SDK_INT = 0 SDK = 29 SEM_PLATFORM_INT = 110500 brand = samsung supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = G965FXXUHFVK1
> 
> Error Message : Permission Denial: writing com.sec.android.app.myfiles.external.providers.MyFilesFileProvider uri content://com.sec.android.app.myfiles.FileProvider/device_storage/Android/data/io.nekohasekai.sfa/Yacd-meta-gh-pages/apple-touch-icon-precomposed.png from pid=7572, uid=11487 requires the provider be exported, or grantUriPermission() Error Cause : null Error StackTrace :
> 
> java.lang.SecurityException: Permission Denial: writing com.sec.android.app.myfiles.external.providers.MyFilesFileProvider uri content://com.sec.android.app.myfiles.FileProvider/device_storage/Android/data/io.nekohasekai.sfa/Yacd-meta-gh-pages/apple-touch-icon-precomposed.png from pid=7572, uid=11487 requires the provider be exported, or grantUriPermission() at android.os.Parcel.createException(Parcel.java:2088) at android.os.Parcel.readException(Parcel.java:2056) at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188) at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151) at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631) at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1535) at android.content.ContentResolver.openOutputStream(ContentResolver.java:1241) at com.rk.xededitor.SimpleEditor.SimpleEditor$save$1.invokeSuspend(SimpleEditor.kt:200) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d2097fd, Dispatchers.IO]
