### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by floviolleau** [Xed-Editor/Xed-Editor#292]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1731247865560
LocalTime : Nov 10, 2024 15:11:05

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = SM-S926B
SEM_INT = 3402
SECURITY_PATCH = 2024-11-01
BASE_OS = samsung/e2sxeea/e2s:14/UP1A.231005.007/S926BXXU3AXH7:user/release-keys
SEM_FIRST_SDK_INT = 34
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150500
brand = samsung
supported_abi = [arm64-v8a]
INCREMENTAL = S926BXXS5AXJ8


Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4172)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4330)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:48)
	at com.rk.settings.PreferencesData.isOled(PreferencesData.kt:39)
	at com.rk.xededitor.ui.theme.ThemeManager.apply(ThemeManager.kt:38)
	at com.rk.xededitor.BaseActivity.onCreate(BaseActivity.kt:24)
	at com.rk.xededitor.MainActivity.MainActivity.onCreate(MainActivity.kt:66)
	at android.app.Activity.performCreate(Activity.java:9001)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4152)
	... 12 more

 ```

**Comment by floviolleau** [comment]
Same as #290
