### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by IamRezaMousavi** [Xed-Editor/Xed-Editor#302]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1731537609193
LocalTime : Nov 14, 2024 02:10:09

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = STK-L21
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2020-08-01
BASE_OS = HUAWEI/STK-L21MDV/HWSTK-HF:10/HUAWEISTK-L21/10.0.0.223C185:user/release-keys
RELEASE = 10
CODENAME = REL
manufacturer = HUAWEI
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 28
PREVIEW_SDK_INT = 0
SDK = 29
brand = HUAWEI
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 10.0.0.274C185


Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8676)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:331)
	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:48)
	at com.rk.settings.PreferencesData.isOled(PreferencesData.kt:39)
	at com.rk.xededitor.ui.theme.ThemeManager.apply(ThemeManager.kt:38)
	at com.rk.xededitor.BaseActivity.onCreate(BaseActivity.kt:24)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:58)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	... 11 more

 ```

**Comment by RohitKushvaha01** [comment]
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1731537609193
> LocalTime : Nov 14, 2024 02:10:09
> 
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = STK-L21
> RESOURCES_SDK_INT = 29
> SECURITY_PATCH = 2020-08-01
> BASE_OS = HUAWEI/STK-L21MDV/HWSTK-HF:10/HUAWEISTK-L21/10.0.0.223C185:user/release-keys
> RELEASE = 10
> CODENAME = REL
> manufacturer = HUAWEI
> SDK_INT = 29
> PREVIEW_SDK_FINGERPRINT = REL
> FIRST_SDK_INT = 28
> PREVIEW_SDK_INT = 0
> SDK = 29
> brand = HUAWEI
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 10.0.0.274C185
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
> 	at android.os.Handler.dispatchMessage(Handler.java:110)
> 	at android.os.Looper.loop(Looper.java:219)
> 	at android.app.ActivityThread.main(ActivityThread.java:8676)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:331)
> 	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:48)
> 	at com.rk.settings.PreferencesData.isOled(PreferencesData.kt:39)
> 	at com.rk.xededitor.ui.theme.ThemeManager.apply(ThemeManager.kt:38)
> 	at com.rk.xededitor.BaseActivity.onCreate(BaseActivity.kt:24)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:58)
> 	at android.app.Activity.performCreate(Activity.java:8214)
> 	at android.app.Activity.performCreate(Activity.java:8202)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
> 	... 11 more
> 
>  ```

Clear app data
