### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [Xed-Editor/Xed-Editor#305]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1731567059405
LocalTime : 14 Nov 2024 06:50:59

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = 23124RA7EO
SECURITY_PATCH = 2024-09-01
BASE_OS = Redmi/sapphiren_eea/sapphiren:14/UKQ1.231207.002/V816.0.5.0.UNHEUXM:user/release-keys
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V816.0.6.0.UNHEUXM


Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3991)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:48)
	at com.rk.settings.PreferencesData.isOled(PreferencesData.kt:39)
	at com.rk.xededitor.ui.theme.ThemeManager.apply(ThemeManager.kt:38)
	at com.rk.xededitor.BaseActivity.onCreate(BaseActivity.kt:24)
	at com.rk.xededitor.MainActivity.MainActivity.onCreate(MainActivity.kt:66)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1485)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3971)
	... 12 more

 ```

**Comment by RohitKushvaha01** [comment]
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1731567059405
> LocalTime : 14 Nov 2024 06:50:59
> 
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = 23124RA7EO
> SECURITY_PATCH = 2024-09-01
> BASE_OS = Redmi/sapphiren_eea/sapphiren:14/UKQ1.231207.002/V816.0.5.0.UNHEUXM:user/release-keys
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> brand = Redmi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V816.0.6.0.UNHEUXM
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.MainActivity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3991)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:224)
> 	at android.os.Looper.loop(Looper.java:318)
> 	at android.app.ActivityThread.main(ActivityThread.java:8763)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
> 	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:48)
> 	at com.rk.settings.PreferencesData.isOled(PreferencesData.kt:39)
> 	at com.rk.xededitor.ui.theme.ThemeManager.apply(ThemeManager.kt:38)
> 	at com.rk.xededitor.BaseActivity.onCreate(BaseActivity.kt:24)
> 	at com.rk.xededitor.MainActivity.MainActivity.onCreate(MainActivity.kt:66)
> 	at android.app.Activity.performCreate(Activity.java:8891)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1485)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3971)
> 	... 12 more
> 
>  ```

Clear app data
