### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kekomenos** [Xed-Editor/Xed-Editor#312]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1731777350764
LocalTime : ۱۶ نوامبر ۲۰۲۴ ۲۰:۴۵:۵۰

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = SM-G965F
SEM_INT = 2903
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2022-03-01
BASE_OS = 
SEM_FIRST_SDK_INT = 26
RELEASE = 10
CODENAME = REL
manufacturer = samsung
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 26
PREVIEW_SDK_INT = 0
SDK = 29
SEM_PLATFORM_INT = 110500
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = G965FXXUHFVK1

Error Message : pattern length must be > 0
Error Cause : null
Error StackTrace : 

java.lang.IllegalArgumentException: pattern length must be > 0
	at io.github.rosemoe.sora.widget.EditorSearcher.search(EditorSearcher.java:110)
	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick.handle$lambda$2$lambda$0(HandleMenuItemClick.kt:50)
	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick.$r8$lambda$y0RD_Uo6X9Zs7QYu4xlj7uUJUVs(Unknown Source:0)
	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1731777350764
> LocalTime : ۱۶ نوامبر ۲۰۲۴ ۲۰:۴۵:۵۰
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = SM-G965F
> SEM_INT = 2903
> RESOURCES_SDK_INT = 29
> SECURITY_PATCH = 2022-03-01
> BASE_OS = 
> SEM_FIRST_SDK_INT = 26
> RELEASE = 10
> CODENAME = REL
> manufacturer = samsung
> SDK_INT = 29
> PREVIEW_SDK_FINGERPRINT = REL
> FIRST_SDK_INT = 26
> PREVIEW_SDK_INT = 0
> SDK = 29
> SEM_PLATFORM_INT = 110500
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = G965FXXUHFVK1
> 
> 
> Error Message : pattern length must be > 0
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.IllegalArgumentException: pattern length must be > 0
> 	at io.github.rosemoe.sora.widget.EditorSearcher.search(EditorSearcher.java:110)
> 	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick.handle$lambda$2$lambda$0(HandleMenuItemClick.kt:50)
> 	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick.$r8$lambda$y0RD_Uo6X9Zs7QYu4xlj7uUJUVs(Unknown Source:0)
> 	at com.rk.xededitor.SimpleEditor.HandleMenuItemClick$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
> 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loop(Looper.java:237)
> 	at android.app.ActivityThread.main(ActivityThread.java:8167)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
> 

Update app
