### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by clear-design** [Xed-Editor/Xed-Editor#315]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1731984569520
LocalTime : Nov 18, 2024 21:49:29

ALL_CODENAMES = [REL]
ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = Pixel 9 Pro
MIN_SUPPORTED_TARGET_SDK_INT = 28
RESOURCES_SDK_INT = 35
SECURITY_PATCH = 2024-11-05
BASE_OS = 
RELEASE = 15
MEDIA_PERFORMANCE_CLASS = 34
CODENAME = REL
manufacturer = Google
RELEASE_OR_CODENAME = 15
RELEASE_OR_PREVIEW_DISPLAY = 15
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 35
PREVIEW_SDK_FINGERPRINT = REL
DEVICE_INITIAL_SDK_INT = 34
PREVIEW_SDK_INT = 0
SDK = 35
brand = google
supported_abi = [arm64-v8a]
INCREMENTAL = 2024110700


Error Message : null
Error Cause : java.net.SocketException: socket failed: EACCES (Permission denied)
Error StackTrace : 

java.lang.ExceptionInInitializerError
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:164)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
	at android.app.Activity.performCreate(Activity.java:9055)
	at android.app.Activity.performCreate(Activity.java:9033)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4043)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4248)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
	at java.net.ServerSocket.createImpl(ServerSocket.java:331)
	at java.net.ServerSocket.getImpl(ServerSocket.java:281)
	at java.net.ServerSocket.bind(ServerSocket.java:399)
	at java.net.ServerSocket.<init>(ServerSocket.java:259)
	at java.net.ServerSocket.<init>(ServerSocket.java:151)
	at com.rk.runner.commonUtils.getAvailablePort(commonUtils.kt:95)
	at com.rk.runner.runners.web.html.HtmlRunner.<init>(HtmlRunner.kt:15)
	at com.rk.runner.Runner.<clinit>(Runner.kt:43)
	... 21 more

 ```

**Comment by RohitKushvaha01** [comment]
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1731984569520
> LocalTime : Nov 18, 2024 21:49:29
> 
> ALL_CODENAMES = [REL]
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = Pixel 9 Pro
> MIN_SUPPORTED_TARGET_SDK_INT = 28
> RESOURCES_SDK_INT = 35
> SECURITY_PATCH = 2024-11-05
> BASE_OS = 
> RELEASE = 15
> MEDIA_PERFORMANCE_CLASS = 34
> CODENAME = REL
> manufacturer = Google
> RELEASE_OR_CODENAME = 15
> RELEASE_OR_PREVIEW_DISPLAY = 15
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
> SDK_INT = 35
> PREVIEW_SDK_FINGERPRINT = REL
> DEVICE_INITIAL_SDK_INT = 34
> PREVIEW_SDK_INT = 0
> SDK = 35
> brand = google
> supported_abi = [arm64-v8a]
> INCREMENTAL = 2024110700
> 
> 
> Error Message : null
> Error Cause : java.net.SocketException: socket failed: EACCES (Permission denied)
> Error StackTrace : 
> 
> java.lang.ExceptionInInitializerError
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:164)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> 	at android.app.Activity.performCreate(Activity.java:9055)
> 	at android.app.Activity.performCreate(Activity.java:9033)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4043)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4248)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
> 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
> 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at android.os.Looper.loopOnce(Looper.java:232)
> 	at android.os.Looper.loop(Looper.java:317)
> 	at android.app.ActivityThread.main(ActivityThread.java:8744)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
> Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
> 	at java.net.ServerSocket.createImpl(ServerSocket.java:331)
> 	at java.net.ServerSocket.getImpl(ServerSocket.java:281)
> 	at java.net.ServerSocket.bind(ServerSocket.java:399)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:259)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:151)
> 	at com.rk.runner.commonUtils.getAvailablePort(commonUtils.kt:95)
> 	at com.rk.runner.runners.web.html.HtmlRunner.<init>(HtmlRunner.kt:15)
> 	at com.rk.runner.Runner.<clinit>(Runner.kt:43)
> 	... 21 more
> 
>  ```

You are trying to access a file that is read only
