### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by zephyrxbps** [Xed-Editor/Xed-Editor#328]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1732670936461
LocalTime : Nov 26, 2024 8:28:56 PM

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = SM-S156V
SEM_INT = 3401
SECURITY_PATCH = 2024-10-01
BASE_OS = samsung/a15xtfn/a15x:14/UP1A.231005.007/S156VUDU3BXG7:user/release-keys
SEM_FIRST_SDK_INT = 34
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = S156VUDS4BXJ2


Error Message : null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException
	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3b888b2, Dispatchers.Main.immediate]

 ```

**Comment by RohitKushvaha01** [comment]
> ```
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1732670936461
> LocalTime : Nov 26, 2024 8:28:56 PM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = SM-S156V
> SEM_INT = 3401
> SECURITY_PATCH = 2024-10-01
> BASE_OS = samsung/a15xtfn/a15x:14/UP1A.231005.007/S156VUDU3BXG7:user/release-keys
> SEM_FIRST_SDK_INT = 34
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> SEM_PLATFORM_INT = 150100
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = S156VUDS4BXJ2
> 
> 
> Error Message : null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
> 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
> 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
> 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
> 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> 	at android.app.Activity.performCreate(Activity.java:8975)
> 	at android.app.Activity.performCreate(Activity.java:8944)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:230)
> 	at android.os.Looper.loop(Looper.java:319)
> 	at android.app.ActivityThread.main(ActivityThread.java:8919)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3b888b2, Dispatchers.Main.immediate]
> ```

update to latest commit
