### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ghostdeveloper404** [Xed-Editor/Xed-Editor#334]
``` 
Fatal Crash occurred on Thread named 'Thread-102'
Unix Time : 1733128199680
LocalTime : 02-Dec-2024 1:59:59 pm

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = SM-A042F
SEM_INT = 3401
SECURITY_PATCH = 2024-10-01
BASE_OS = samsung/a04exx/a04e:14/UP1A.231005.007/A042FXXU7EXE3:user/release-keys
SEM_FIRST_SDK_INT = 31
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = A042FXXSAEXJ3


Error Message : null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException
	at com.rk.runner.runners.node.NodeRunner.run$lambda$0(NodeRunner.kt:18)
	at com.rk.runner.runners.node.NodeRunner.$r8$lambda$QbWlCpD5O-5fEHdv9Si_yXWrMOo(Unknown Source:0)
	at com.rk.runner.runners.node.NodeRunner$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at com.rk.runner.commonUtils.exctractAssets(commonUtils.kt:36)
	at com.rk.runner.runners.node.NodeRunner.run(NodeRunner.kt:13)
	at com.rk.runner.Runner$run$1.invokeSuspend$lambda$0(Runner.kt:73)
	at com.rk.runner.Runner$run$1.$r8$lambda$4TBkaQs8rO7JAC2X1-mv8lh2mbs(Unknown Source:0)
	at com.rk.runner.Runner$run$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

 ```

**Comment by RohitKushvaha01** [comment]
update the app

**Comment by ghostdeveloper404** [comment]
I updated then this is happened ok

**Comment by ghostdeveloper404** [comment]
> I updated then this is happened ok
"After updating the app, it now opens in my default browser instead of the developer browser I was using before the update. The APK was previously set to use the developer browser. How can I fix this and make it use the developer browser again?"
