### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Masrkai** [Xed-Editor/Xed-Editor#365]
I was trying to open syncthing ignore patterns through this application on my device which resulted in opening the app, crashing it, then getting back to syncthing.

Then i opened the recent apps to find that the text editor has this error message and asking me to report it so i did and here it's:

``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1733852056235
LocalTime : Dec 10, 2024 7:34:16 PM

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = SM-A715F
SEM_INT = 3301
SECURITY_PATCH = 2024-02-01
BASE_OS = samsung/a71naxx/a71:13/TP1A.220624.014/A715FXXUADWH4:user/release-keys
SEM_FIRST_SDK_INT = 29
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
SEM_PLATFORM_INT = 140100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = A715FXXSBDXB1


Error Message : null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException
	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1e2d59c, Dispatchers.Main.immediate]

 ```

**Comment by RohitKushvaha01** [comment]
> I was trying to open syncthing ignore patterns through this application on my device which resulted in opening the app, crashing it, then getting back to syncthing.
> 
> Then i opened the recent apps to find that the text editor has this error message and asking me to report it so i did and here it's:
> 
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1733852056235
> LocalTime : Dec 10, 2024 7:34:16 PM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = SM-A715F
> SEM_INT = 3301
> SECURITY_PATCH = 2024-02-01
> BASE_OS = samsung/a71naxx/a71:13/TP1A.220624.014/A715FXXUADWH4:user/release-keys
> SEM_FIRST_SDK_INT = 29
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> SEM_PLATFORM_INT = 140100
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = A715FXXSBDXB1
> 
> 
> Error Message : null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
> 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
> 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
> 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
> 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> 	at android.app.Activity.performCreate(Activity.java:8591)
> 	at android.app.Activity.performCreate(Activity.java:8570)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8762)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1e2d59c, Dispatchers.Main.immediate]
> 
>  ```

This crash is already fixed in testing builds
You can download it from github actions

https://github.com/Xed-Editor/Xed-Editor/actions/runs/12256638966#artifacts
