### ISSUE TITLE
Crash Report, opening txt file from zip file

### ISSUE THREAD

**Issue by wierzpio** [Xed-Editor/Xed-Editor#387]
``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1735232891750
git commit hash : 1680e4e8
git commit date : 2024-12-14T10:25:03+05:30
LocalTime : Dec 26, 2024 12:08:11

ACTIVE_CODENAMES = []
app_version = 2.9.0
device_model = Pixel 7
SECURITY_PATCH = 2024-12-05
BASE_OS = 
RELEASE = 15
MEDIA_PERFORMANCE_CLASS = 33
CODENAME = REL
manufacturer = Google
RELEASE_OR_CODENAME = 15
RELEASE_OR_PREVIEW_DISPLAY = 15
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 35
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 35
brand = google
supported_abi = [arm64-v8a]
INCREMENTAL = 12621605


Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.externaleditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.externaleditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4129)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4316)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:353)
	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:29)
	at com.rk.externaleditor.SimpleEditor.setupInputView(SimpleEditor.kt:110)
	at com.rk.externaleditor.SimpleEditor.onCreate(SimpleEditor.kt:75)
	at android.app.Activity.performCreate(Activity.java:9019)
	at android.app.Activity.performCreate(Activity.java:8997)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1528)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
	... 13 more

 ```

**Comment by RohitKushvaha01** [comment]
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1735232891750
> git commit hash : 1680e4e8
> git commit date : 2024-12-14T10:25:03+05:30
> LocalTime : Dec 26, 2024 12:08:11
> 
> ACTIVE_CODENAMES = []
> app_version = 2.9.0
> device_model = Pixel 7
> SECURITY_PATCH = 2024-12-05
> BASE_OS = 
> RELEASE = 15
> MEDIA_PERFORMANCE_CLASS = 33
> CODENAME = REL
> manufacturer = Google
> RELEASE_OR_CODENAME = 15
> RELEASE_OR_PREVIEW_DISPLAY = 15
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
> SDK_INT = 35
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 35
> brand = google
> supported_abi = [arm64-v8a]
> INCREMENTAL = 12621605
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.externaleditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.externaleditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4129)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4316)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
> 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
> 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
> 	at android.os.Handler.dispatchMessage(Handler.java:109)
> 	at android.os.Looper.loopOnce(Looper.java:232)
> 	at android.os.Looper.loop(Looper.java:317)
> 	at android.app.ActivityThread.main(ActivityThread.java:8787)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:353)
> 	at com.rk.settings.PreferencesData.getBoolean(PreferencesData.kt:29)
> 	at com.rk.externaleditor.SimpleEditor.setupInputView(SimpleEditor.kt:110)
> 	at com.rk.externaleditor.SimpleEditor.onCreate(SimpleEditor.kt:75)
> 	at android.app.Activity.performCreate(Activity.java:9019)
> 	at android.app.Activity.performCreate(Activity.java:8997)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1528)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
> 	... 13 more
> 
>  ```

Clear app data to fix the issue
