### ISSUE TITLE
Crash Report (file writing issue with Google files)

### ISSUE THREAD

**Issue by MuhammadBayiz** [Xed-Editor/Xed-Editor#42]
Fatal Crash occurred on Thread named 'Thread-73'
Unix Time : 1721740389355
LocalTime : Jul 23, 2024 16:13:09

ACTIVE_CODENAMES = []
app_version = 2.4.3
device_model = Mi 9T
SECURITY_PATCH = 2024-06-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = eng.celest.20240628.193921

Error Message : Permission Denial: writing com.google.android.libraries.storage.storagelib.FileProvider uri content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDocuments%2Fnotification-silencer.sh from pid=25671, uid=10261 requires the provider be exported, or grantUriPermission()
Error Cause : null
Error StackTrace : 

java.lang.SecurityException: Permission Denial: writing com.google.android.libraries.storage.storagelib.FileProvider uri content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDocuments%2Fnotification-silencer.sh from pid=25671, uid=10261 requires the provider be exported, or grantUriPermission()
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:202)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:165)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1876)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1574)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.lambda$save$3(SimpleEditor.java:264)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.$r8$lambda$1dMwrvGOWmy15sn56jsM5sS8ftc(Unknown Source:0)
	at com.rk.xededitor.SimpleEditor.SimpleEditor$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by RohitKushvaha01** [comment]
> Can't save opened files from google files some write permission denied 

That's not a issue with xed the file provided is read only

**Comment by MuhammadBayiz** [comment]
Any updates on this issue? It's really annoying it would be much easier if i could just open the files from the google files. This issue doesn't occur with other text editors such as (QuickEdit, Mixplorer's Text editor)

**Comment by GitProHub-stacked** [comment]
Since he marked as duplicate, Did you try using 2.9.5? I only get the error in 2.9.6.

**Comment by MuhammadBayiz** [comment]
> Since he marked as duplicate, Did you try using 2.9.5? I only get the error in 2.9.6.

In 2.9.5 the bug doesn't occur

**Comment by MuhammadBayiz** [comment]
2.9.6 says "Permission Denied" so the same bug perhaps

**Comment by GitProHub-stacked** [comment]
Was it for python file or some other file?

**Comment by MuhammadBayiz** [comment]
> Was it for python file or some other file?

A .txt file, i believe it happens for any text bases file
